### ISSUE TITLE
How to use with route params

### ISSUE THREAD

**Issue by vinaypuppal** [sanfilippopablo/react-swipeable-routes#4]
```html
<div id="app">
 <header className={style.header}>
 <div className="container">
  <h1>Pollvap</h1>
  <nav>
  <Link activeClassName={style.active} to="/">Home</Link>
  <Link activeClassName={style.active} to="/profile">Me</Link>
  <Link activeClassName={style.active} to="/profile/john">John</Link>
 </nav>
 </div>
 </header>
 <SwipeableRoutes enableMouseEvents>
    <Route exact component={Home} path="/" />
    <Route exact component={Profile} path="/profile/" user="me" />
    <Route component={Profile} path="/profile/:user" />
 </SwipeableRoutes>
</div>
```
- How to set `user` param during swipe
- And also `match` prop is undefined on rendered component i.e I cant access `this.props.match.params.user` when user clicks `<Link activeClassName={style.active} to="/profile/john">John</Link>`

**Comment by sanfilippopablo** [comment]
Hello! Thank you for taking the time to file this issue.

The `undefined` `match` prop is a bug.
The lib is not currently compatible with routes with params, but now it is a good time to add support. I'll try and solve both of these issues over the weekend. If you have any thoughts on how would you like the API to be, feel free to post them here. (For example, what would the expected behavior be when swiping to a route with params?)

**Comment by sanfilippopablo** [comment]
You can now use paths with params in the last version. Install it using `npm install react-swipeable-routes@0.4.0-beta.2`. You can check docs [here](https://github.com/sanfilippopablo/react-swipeable-routes/tree/path-with-params)

**Comment by vinaypuppal** [comment]
Awesome 🎉 
Thanks for implementing it.

I tried `react-swipeable-routes@0.4.0-beta.3` with new route params example as shown in docs. Getting an error `Cannot read property 'params' of undefined`. You can view same at this link
 https://codesandbox.io/s/724j0n8qo6

**Comment by sanfilippopablo** [comment]
OK, it should be working now. Try with `react-swipeable-routes@0.4.0-beta.5`

**Comment by vinaypuppal** [comment]
Yeah its working! 
Thanks
