### ISSUE TITLE
ScrollToTop

### ISSUE THREAD

**Issue by Ouzii** [sanfilippopablo/react-swipeable-routes#6]
Hello,
do you have any tips how to get the page scrolled to top on swipe? Been trying to do this for a project and haven't had any luck with the tips at https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/scroll-restoration.md or
anywhere else. Thanks in advance.

**Comment by sanfilippopablo** [comment]
@Ouzii Hello! I just read that page and that shouldn't work, because it's trying to scroll to top the window object, while here we need to scroll the container object. This is an issue related to react-swipeable-views. I have already filed an issue for that: https://github.com/oliviertassinari/react-swipeable-views/issues/424

**Comment by Ouzii** [comment]
@sanfilippopablo Ok, thank you very much! I'll wait and see how are they going to reply to your issue.

**Comment by sanfilippopablo** [comment]
This is probably not useful to you anymore, but I added a code example in the README on how to do this: https://github.com/sanfilippopablo/react-swipeable-routes#scroll-to-top-on-swipe .
